// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewnreiyrqunjupyvksxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3bnJlaXlycXVuanVweXZrc3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDExNTIsImV4cCI6MjA2NzU3NzE1Mn0.mZ3VGOkSD1DxXFW8i9XFTq7u4Z3aKlwI9VZ40-m1OuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});